//! DuckDB's SIMPLE case mapping, as measured — see scripts/gen_casemap.py
//! for the full story (simple-vs-full mapping, Unicode version skew, and why
//! a dependency would be the wrong spec twice over).
//!
//! GENERATED by `uv run python scripts/gen_casemap.py` against duckdb-python
//! 1.5.5; regenerate after a duckdb bump. The full-codepoint census in
//! tests/test_duckdb_interpreter.py fails loudly if this table drifts from
//! the duckdb the suite runs against — the census, not this file, is the
//! authority.
//!
//! Entries are (codepoint, mapped) pairs, sorted by codepoint, covering only
//! the codepoints where the dependency-free fallback (Rust's full map iff it
//! is 1:1, else identity) disagrees with DuckDB. Everything else goes through
//! the fallback in `simple_upper`/`simple_lower`.

/// Simple uppercase for one codepoint, exactly as DuckDB computes it.
pub fn simple_upper(c: char) -> char {
    if let Ok(i) = UPPER_EXCEPTIONS.binary_search_by_key(&c, |e| e.0) {
        return UPPER_EXCEPTIONS[i].1;
    }
    let mut it = c.to_uppercase();
    let first = it.next().expect("case iterators are non-empty");
    if it.next().is_none() {
        first
    } else {
        c
    }
}

/// Simple lowercase for one codepoint, exactly as DuckDB computes it.
pub fn simple_lower(c: char) -> char {
    if let Ok(i) = LOWER_EXCEPTIONS.binary_search_by_key(&c, |e| e.0) {
        return LOWER_EXCEPTIONS[i].1;
    }
    let mut it = c.to_lowercase();
    let first = it.next().expect("case iterators are non-empty");
    if it.next().is_none() {
        first
    } else {
        c
    }
}

pub(super) const UPPER_EXCEPTIONS: &[(char, char)] = &[
    ('\u{00DF}', '\u{1E9E}'),   // 'ß' -> 'ẞ'
    ('\u{019B}', '\u{019B}'),   // 'ƛ' -> 'ƛ'
    ('\u{0264}', '\u{0264}'),   // 'ɤ' -> 'ɤ'
    ('\u{1C8A}', '\u{1C8A}'),   // 'ᲊ' -> 'ᲊ'
    ('\u{1F80}', '\u{1F88}'),   // 'ᾀ' -> 'ᾈ'
    ('\u{1F81}', '\u{1F89}'),   // 'ᾁ' -> 'ᾉ'
    ('\u{1F82}', '\u{1F8A}'),   // 'ᾂ' -> 'ᾊ'
    ('\u{1F83}', '\u{1F8B}'),   // 'ᾃ' -> 'ᾋ'
    ('\u{1F84}', '\u{1F8C}'),   // 'ᾄ' -> 'ᾌ'
    ('\u{1F85}', '\u{1F8D}'),   // 'ᾅ' -> 'ᾍ'
    ('\u{1F86}', '\u{1F8E}'),   // 'ᾆ' -> 'ᾎ'
    ('\u{1F87}', '\u{1F8F}'),   // 'ᾇ' -> 'ᾏ'
    ('\u{1F90}', '\u{1F98}'),   // 'ᾐ' -> 'ᾘ'
    ('\u{1F91}', '\u{1F99}'),   // 'ᾑ' -> 'ᾙ'
    ('\u{1F92}', '\u{1F9A}'),   // 'ᾒ' -> 'ᾚ'
    ('\u{1F93}', '\u{1F9B}'),   // 'ᾓ' -> 'ᾛ'
    ('\u{1F94}', '\u{1F9C}'),   // 'ᾔ' -> 'ᾜ'
    ('\u{1F95}', '\u{1F9D}'),   // 'ᾕ' -> 'ᾝ'
    ('\u{1F96}', '\u{1F9E}'),   // 'ᾖ' -> 'ᾞ'
    ('\u{1F97}', '\u{1F9F}'),   // 'ᾗ' -> 'ᾟ'
    ('\u{1FA0}', '\u{1FA8}'),   // 'ᾠ' -> 'ᾨ'
    ('\u{1FA1}', '\u{1FA9}'),   // 'ᾡ' -> 'ᾩ'
    ('\u{1FA2}', '\u{1FAA}'),   // 'ᾢ' -> 'ᾪ'
    ('\u{1FA3}', '\u{1FAB}'),   // 'ᾣ' -> 'ᾫ'
    ('\u{1FA4}', '\u{1FAC}'),   // 'ᾤ' -> 'ᾬ'
    ('\u{1FA5}', '\u{1FAD}'),   // 'ᾥ' -> 'ᾭ'
    ('\u{1FA6}', '\u{1FAE}'),   // 'ᾦ' -> 'ᾮ'
    ('\u{1FA7}', '\u{1FAF}'),   // 'ᾧ' -> 'ᾯ'
    ('\u{1FB3}', '\u{1FBC}'),   // 'ᾳ' -> 'ᾼ'
    ('\u{1FC3}', '\u{1FCC}'),   // 'ῃ' -> 'ῌ'
    ('\u{1FF3}', '\u{1FFC}'),   // 'ῳ' -> 'ῼ'
    ('\u{A7CD}', '\u{A7CD}'),   // 'ꟍ' -> 'ꟍ'
    ('\u{A7CF}', '\u{A7CF}'),   // '\ua7cf' -> '\ua7cf'
    ('\u{A7D3}', '\u{A7D3}'),   // 'ꟓ' -> 'ꟓ'
    ('\u{A7D5}', '\u{A7D5}'),   // 'ꟕ' -> 'ꟕ'
    ('\u{A7DB}', '\u{A7DB}'),   // 'ꟛ' -> 'ꟛ'
    ('\u{10D70}', '\u{10D70}'), // '𐵰' -> '𐵰'
    ('\u{10D71}', '\u{10D71}'), // '𐵱' -> '𐵱'
    ('\u{10D72}', '\u{10D72}'), // '𐵲' -> '𐵲'
    ('\u{10D73}', '\u{10D73}'), // '𐵳' -> '𐵳'
    ('\u{10D74}', '\u{10D74}'), // '𐵴' -> '𐵴'
    ('\u{10D75}', '\u{10D75}'), // '𐵵' -> '𐵵'
    ('\u{10D76}', '\u{10D76}'), // '𐵶' -> '𐵶'
    ('\u{10D77}', '\u{10D77}'), // '𐵷' -> '𐵷'
    ('\u{10D78}', '\u{10D78}'), // '𐵸' -> '𐵸'
    ('\u{10D79}', '\u{10D79}'), // '𐵹' -> '𐵹'
    ('\u{10D7A}', '\u{10D7A}'), // '𐵺' -> '𐵺'
    ('\u{10D7B}', '\u{10D7B}'), // '𐵻' -> '𐵻'
    ('\u{10D7C}', '\u{10D7C}'), // '𐵼' -> '𐵼'
    ('\u{10D7D}', '\u{10D7D}'), // '𐵽' -> '𐵽'
    ('\u{10D7E}', '\u{10D7E}'), // '𐵾' -> '𐵾'
    ('\u{10D7F}', '\u{10D7F}'), // '𐵿' -> '𐵿'
    ('\u{10D80}', '\u{10D80}'), // '𐶀' -> '𐶀'
    ('\u{10D81}', '\u{10D81}'), // '𐶁' -> '𐶁'
    ('\u{10D82}', '\u{10D82}'), // '𐶂' -> '𐶂'
    ('\u{10D83}', '\u{10D83}'), // '𐶃' -> '𐶃'
    ('\u{10D84}', '\u{10D84}'), // '𐶄' -> '𐶄'
    ('\u{10D85}', '\u{10D85}'), // '𐶅' -> '𐶅'
    ('\u{16EBB}', '\u{16EBB}'), // '\U00016ebb' -> '\U00016ebb'
    ('\u{16EBC}', '\u{16EBC}'), // '\U00016ebc' -> '\U00016ebc'
    ('\u{16EBD}', '\u{16EBD}'), // '\U00016ebd' -> '\U00016ebd'
    ('\u{16EBE}', '\u{16EBE}'), // '\U00016ebe' -> '\U00016ebe'
    ('\u{16EBF}', '\u{16EBF}'), // '\U00016ebf' -> '\U00016ebf'
    ('\u{16EC0}', '\u{16EC0}'), // '\U00016ec0' -> '\U00016ec0'
    ('\u{16EC1}', '\u{16EC1}'), // '\U00016ec1' -> '\U00016ec1'
    ('\u{16EC2}', '\u{16EC2}'), // '\U00016ec2' -> '\U00016ec2'
    ('\u{16EC3}', '\u{16EC3}'), // '\U00016ec3' -> '\U00016ec3'
    ('\u{16EC4}', '\u{16EC4}'), // '\U00016ec4' -> '\U00016ec4'
    ('\u{16EC5}', '\u{16EC5}'), // '\U00016ec5' -> '\U00016ec5'
    ('\u{16EC6}', '\u{16EC6}'), // '\U00016ec6' -> '\U00016ec6'
    ('\u{16EC7}', '\u{16EC7}'), // '\U00016ec7' -> '\U00016ec7'
    ('\u{16EC8}', '\u{16EC8}'), // '\U00016ec8' -> '\U00016ec8'
    ('\u{16EC9}', '\u{16EC9}'), // '\U00016ec9' -> '\U00016ec9'
    ('\u{16ECA}', '\u{16ECA}'), // '\U00016eca' -> '\U00016eca'
    ('\u{16ECB}', '\u{16ECB}'), // '\U00016ecb' -> '\U00016ecb'
    ('\u{16ECC}', '\u{16ECC}'), // '\U00016ecc' -> '\U00016ecc'
    ('\u{16ECD}', '\u{16ECD}'), // '\U00016ecd' -> '\U00016ecd'
    ('\u{16ECE}', '\u{16ECE}'), // '\U00016ece' -> '\U00016ece'
    ('\u{16ECF}', '\u{16ECF}'), // '\U00016ecf' -> '\U00016ecf'
    ('\u{16ED0}', '\u{16ED0}'), // '\U00016ed0' -> '\U00016ed0'
    ('\u{16ED1}', '\u{16ED1}'), // '\U00016ed1' -> '\U00016ed1'
    ('\u{16ED2}', '\u{16ED2}'), // '\U00016ed2' -> '\U00016ed2'
    ('\u{16ED3}', '\u{16ED3}'), // '\U00016ed3' -> '\U00016ed3'
];

pub(super) const LOWER_EXCEPTIONS: &[(char, char)] = &[
    ('\u{0130}', '\u{0069}'),   // 'İ' -> 'i'
    ('\u{1C89}', '\u{1C89}'),   // 'Ᲊ' -> 'Ᲊ'
    ('\u{A7CB}', '\u{A7CB}'),   // 'Ɤ' -> 'Ɤ'
    ('\u{A7CC}', '\u{A7CC}'),   // 'Ꟍ' -> 'Ꟍ'
    ('\u{A7CE}', '\u{A7CE}'),   // '\ua7ce' -> '\ua7ce'
    ('\u{A7D2}', '\u{A7D2}'),   // '\ua7d2' -> '\ua7d2'
    ('\u{A7D4}', '\u{A7D4}'),   // '\ua7d4' -> '\ua7d4'
    ('\u{A7DA}', '\u{A7DA}'),   // 'Ꟛ' -> 'Ꟛ'
    ('\u{A7DC}', '\u{A7DC}'),   // 'Ƛ' -> 'Ƛ'
    ('\u{10D50}', '\u{10D50}'), // '𐵐' -> '𐵐'
    ('\u{10D51}', '\u{10D51}'), // '𐵑' -> '𐵑'
    ('\u{10D52}', '\u{10D52}'), // '𐵒' -> '𐵒'
    ('\u{10D53}', '\u{10D53}'), // '𐵓' -> '𐵓'
    ('\u{10D54}', '\u{10D54}'), // '𐵔' -> '𐵔'
    ('\u{10D55}', '\u{10D55}'), // '𐵕' -> '𐵕'
    ('\u{10D56}', '\u{10D56}'), // '𐵖' -> '𐵖'
    ('\u{10D57}', '\u{10D57}'), // '𐵗' -> '𐵗'
    ('\u{10D58}', '\u{10D58}'), // '𐵘' -> '𐵘'
    ('\u{10D59}', '\u{10D59}'), // '𐵙' -> '𐵙'
    ('\u{10D5A}', '\u{10D5A}'), // '𐵚' -> '𐵚'
    ('\u{10D5B}', '\u{10D5B}'), // '𐵛' -> '𐵛'
    ('\u{10D5C}', '\u{10D5C}'), // '𐵜' -> '𐵜'
    ('\u{10D5D}', '\u{10D5D}'), // '𐵝' -> '𐵝'
    ('\u{10D5E}', '\u{10D5E}'), // '𐵞' -> '𐵞'
    ('\u{10D5F}', '\u{10D5F}'), // '𐵟' -> '𐵟'
    ('\u{10D60}', '\u{10D60}'), // '𐵠' -> '𐵠'
    ('\u{10D61}', '\u{10D61}'), // '𐵡' -> '𐵡'
    ('\u{10D62}', '\u{10D62}'), // '𐵢' -> '𐵢'
    ('\u{10D63}', '\u{10D63}'), // '𐵣' -> '𐵣'
    ('\u{10D64}', '\u{10D64}'), // '𐵤' -> '𐵤'
    ('\u{10D65}', '\u{10D65}'), // '𐵥' -> '𐵥'
    ('\u{16EA0}', '\u{16EA0}'), // '\U00016ea0' -> '\U00016ea0'
    ('\u{16EA1}', '\u{16EA1}'), // '\U00016ea1' -> '\U00016ea1'
    ('\u{16EA2}', '\u{16EA2}'), // '\U00016ea2' -> '\U00016ea2'
    ('\u{16EA3}', '\u{16EA3}'), // '\U00016ea3' -> '\U00016ea3'
    ('\u{16EA4}', '\u{16EA4}'), // '\U00016ea4' -> '\U00016ea4'
    ('\u{16EA5}', '\u{16EA5}'), // '\U00016ea5' -> '\U00016ea5'
    ('\u{16EA6}', '\u{16EA6}'), // '\U00016ea6' -> '\U00016ea6'
    ('\u{16EA7}', '\u{16EA7}'), // '\U00016ea7' -> '\U00016ea7'
    ('\u{16EA8}', '\u{16EA8}'), // '\U00016ea8' -> '\U00016ea8'
    ('\u{16EA9}', '\u{16EA9}'), // '\U00016ea9' -> '\U00016ea9'
    ('\u{16EAA}', '\u{16EAA}'), // '\U00016eaa' -> '\U00016eaa'
    ('\u{16EAB}', '\u{16EAB}'), // '\U00016eab' -> '\U00016eab'
    ('\u{16EAC}', '\u{16EAC}'), // '\U00016eac' -> '\U00016eac'
    ('\u{16EAD}', '\u{16EAD}'), // '\U00016ead' -> '\U00016ead'
    ('\u{16EAE}', '\u{16EAE}'), // '\U00016eae' -> '\U00016eae'
    ('\u{16EAF}', '\u{16EAF}'), // '\U00016eaf' -> '\U00016eaf'
    ('\u{16EB0}', '\u{16EB0}'), // '\U00016eb0' -> '\U00016eb0'
    ('\u{16EB1}', '\u{16EB1}'), // '\U00016eb1' -> '\U00016eb1'
    ('\u{16EB2}', '\u{16EB2}'), // '\U00016eb2' -> '\U00016eb2'
    ('\u{16EB3}', '\u{16EB3}'), // '\U00016eb3' -> '\U00016eb3'
    ('\u{16EB4}', '\u{16EB4}'), // '\U00016eb4' -> '\U00016eb4'
    ('\u{16EB5}', '\u{16EB5}'), // '\U00016eb5' -> '\U00016eb5'
    ('\u{16EB6}', '\u{16EB6}'), // '\U00016eb6' -> '\U00016eb6'
    ('\u{16EB7}', '\u{16EB7}'), // '\U00016eb7' -> '\U00016eb7'
    ('\u{16EB8}', '\u{16EB8}'), // '\U00016eb8' -> '\U00016eb8'
];
