"""Extract DuckDB's own pow(10, k) table into
packages/confit/src/specializer/exec/pow10.rs.

round(x, n) / trunc(x, n) scale by the DuckDB binary's std::pow(10, n),
which is neither correctly rounded (k=23 is one ulp above strtod's 1e23)
nor any fixed libm we can call at runtime — so the scale factors are
extracted from the oracle itself and baked as bit-exact constants, the
same playbook as the case-map exception table.

Run: uv run python scripts/gen_pow10.py   (idempotent)
"""

from __future__ import annotations

import struct
from pathlib import Path

import duckdb

OUT = (
    Path(__file__).parent.parent
    / "packages"
    / "confit"
    / "src"
    / "specializer"
    / "exec"
    / "pow10.rs"
)

# Witnesses measured 2026-07-26 (wave-1 pins): the table is NOT float("1e{k}")
# everywhere, and NOT ucrt pow everywhere — both must hold or extraction broke.
WITNESSES = {23: 0x44B52D02C7E14AF7, 126: 0x5A17A2ECC414A03F}


def main() -> None:
    con = duckdb.connect()
    bits: list[int] = []
    for k in range(309):
        (v,) = con.execute("SELECT pow(10.0, CAST(? AS DOUBLE))", [k]).fetchone()
        bits.append(struct.unpack("<Q", struct.pack("<d", v))[0])

    for k, want in WITNESSES.items():
        assert bits[k] == want, (
            f"pow10({k}) extracted as {bits[k]:#018x}, pinned {want:#018x} — "
            "DuckDB version drift? Re-measure the pins before regenerating."
        )

    lines = [
        "//! GENERATED by scripts/gen_pow10.py — do not edit.",
        "//!",
        "//! DuckDB 1.5.5's own std::pow(10, k) for k in 0..=308, bit-exact",
        "//! (k=23 is one ulp above strtod 1e23; see the wave-1 pins spec).",
        "//! round(x, n)/trunc(x, n) must scale by THESE values, never a",
        "//! runtime powi/powf.",
        "",
        "pub(super) const POW10: [f64; 309] = [",
    ]
    for k, b in enumerate(bits):
        lines.append(f"    f64::from_bits(0x{b:016X}), // 1e{k}")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(bits)} entries, witnesses ok)")


if __name__ == "__main__":
    main()
